---
- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add repository for PHP versions (Ubuntu).
  apt_repository:
    repo: "ppa:ondrej/php/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install php packages (apt)
  apt:
    name: "{{ php_packages }}"
    state: latest
    update_cache: yes

- name: Update cache after adding PHP packages.
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install php-fpm packages
  apt:
    name: "{{ php_fpm_packages }}"
    state: latest
    update_cache: yes
  when: install_php_fpm

- name: Load custom php-fpm service configuration
  copy:
    src: "php-fpm"
    dest: "/etc/init.d/{{ php_fpm_service_file }}"
    backup: yes
    owner: root
    group: root
    mode: '0755'
  notify:
    - start php-fpm
  when: install_php_fpm
  
- name: Make php-fpm service file work across all versions
  lineinfile:
    path: "/etc/init.d/{{ php_fpm_service_file }}"
    regexp: '^CONFFILE=/etc/php/php-version/fpm/php-fpm.conf'
    line: "CONFFILE={{ php_fpm_conf_path }}/php-fpm.conf"
    backup: yes
    owner: root
    group: root
    mode: '0755'
  when: install_php_fpm

- name: Make php-fpm.conf work across all versions
  lineinfile:
    path: "{{ php_fpm_conf_path }}/php-fpm.conf"
    regexp: '^include=/etc/php/php-version/fpm/pool.d/*.conf'
    line: "include=/etc/php/{{ php_version }}/fpm/pool.d/*.conf"
    backup: yes
    owner: root
    group: root
    mode: '0644'
  when: install_php_fpm

- name: Install php-fpm pool configuration
  copy:
    src: "{{ php_fpm_pool_file }}" 
    dest: "{{ php_fpm_pool_conf_path }}"
    backup: yes
    owner: root
    group: root
    mode: '0644'
  notify: 
  - reload php-fpm
  when: install_php_fpm
    
